name: Karate API Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "qa"
        type: choice
        options:
          - dev
          - qa
          - prod

      test_suite:
        description: "Test Suite"
        required: true
        default: "smoke"
        type: choice
        options:
          - smoke
          - full

jobs:
  karate-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run Karate tests
        run: |
          if [ "${{ github.event.inputs.test_suite }}" = "smoke" ]; then
            mvn clean test \
              -Dtest=PizzaSmokeRunner \
              -Dkarate.env=${{ github.event.inputs.environment || 'qa' }}
          else
            mvn clean test \
              -Dtest=PizzaRunner \
              -Dkarate.env=${{ github.event.inputs.environment || 'qa' }}
          fi

      - name: Upload Karate reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports/
          retention-days: 14